#ifndef UI_HTML_H
#define UI_HTML_H

/* index.html is gzip-compressed at build time and embedded as a binary blob.
 * The symbols below are generated by the IDF build system via EMBED_FILES.
 * Serve with Content-Encoding: gzip and Content-Type: text/html.
 */
extern const uint8_t index_html_gz_start[] asm("_binary_index_html_gz_start");
extern const uint8_t index_html_gz_end[]   asm("_binary_index_html_gz_end");

#endif /* UI_HTML_H */
